import { describe, expect, it } from "vitest";

import {
  element,
  findVirtualNodeProblems,
  fragment,
  isValidVirtualNode,
  normalizeAttributes,
  normalizeChildren,
  text,
  trustedHtml,
  type VirtualNode,
} from "./virtual-tree.js";

describe("element", () => {
  it("builds nested elements", () => {
    const tree = element(
      "article",
      { class: "page" },
      element("h1", {}, "Title"),
      element("p", {}, "Body"),
    );

    expect(tree.tag).toBe("article");
    expect(tree.attributes).toEqual({ class: "page" });
    expect(tree.children).toHaveLength(2);
    expect(tree.children[0]).toEqual({
      type: "element",
      tag: "h1",
      attributes: {},
      children: [{ type: "text", value: "Title" }],
    });
  });

  it("needs no attributes or children", () => {
    expect(element("hr")).toEqual({
      type: "element",
      tag: "hr",
      attributes: {},
      children: [],
    });
  });
});

describe("attribute normalization", () => {
  it("keeps strings and converts numbers", () => {
    expect(normalizeAttributes({ id: "a", tabindex: -1 })).toEqual({
      id: "a",
      tabindex: "-1",
    });
  });

  it("turns true into a bare boolean attribute", () => {
    expect(normalizeAttributes({ hidden: true })).toEqual({ hidden: true });
  });

  it.each([
    ["false", false],
    ["null", null],
    ["undefined", undefined],
  ])("removes an attribute whose value is %s", (_label, value) => {
    // `hidden="false"` is read by HTML as hidden, so emitting it would do the
    // opposite of what the theme asked for.
    expect(normalizeAttributes({ hidden: value })).toEqual({});
  });

  it("orders attributes deterministically", () => {
    // Attribute order carries no meaning in HTML, and unstable order makes
    // output undiffable and content-hash caching useless.
    const forwards = normalizeAttributes({ z: "1", a: "2", m: "3" });
    const backwards = normalizeAttributes({ m: "3", z: "1", a: "2" });

    expect(Object.keys(forwards)).toEqual(["a", "m", "z"]);
    expect(Object.keys(backwards)).toEqual(Object.keys(forwards));
  });

  it("keeps an empty string, which is a meaningful value", () => {
    expect(normalizeAttributes({ alt: "" })).toEqual({ alt: "" });
  });
});

describe("child normalization", () => {
  it("wraps strings and numbers as text", () => {
    expect(normalizeChildren(["a", 1])).toEqual([
      { type: "text", value: "a" },
      { type: "text", value: "1" },
    ]);
  });

  it.each([
    ["null", null],
    ["undefined", undefined],
    ["false", false],
    ["true", true],
  ])("drops a child that is %s", (_label, child) => {
    // `true` only ever arrives from a mistyped conditional, and rendering the
    // word "true" into a page helps nobody.
    expect(normalizeChildren([child])).toEqual([]);
  });

  it("drops empty strings so trees stay comparable", () => {
    expect(normalizeChildren(["", "a"])).toEqual([
      { type: "text", value: "a" },
    ]);
  });

  it("flattens arrays, so a mapped list needs no spread", () => {
    expect(normalizeChildren([["a", "b"], "c"])).toEqual([
      { type: "text", value: "a" },
      { type: "text", value: "b" },
      { type: "text", value: "c" },
    ]);
  });

  it("flattens deeply nested arrays", () => {
    expect(normalizeChildren([[["a"], ["b"]]])).toHaveLength(2);
  });

  it("supports a conditional child written inline", () => {
    const isDraft = false;
    const tree = element(
      "p",
      {},
      isDraft && element("span", {}, "Draft"),
      "Body",
    );

    expect(tree.children).toEqual([{ type: "text", value: "Body" }]);
  });

  it("keeps a fragment as a node rather than flattening it away", () => {
    const tree = element("div", {}, fragment("a", fragment("b")));

    expect(tree.children[0]?.type).toBe("fragment");
    expect(tree.children).toHaveLength(1);
  });

  it("handles an empty fragment", () => {
    expect(fragment()).toEqual({ type: "fragment", children: [] });
  });
});

describe("trusted HTML", () => {
  it("is a distinct type, not a string", () => {
    // The safety property: a theme cannot emit unescaped output by forgetting
    // something. It has to ask, in a call that requires a reason.
    const node = trustedHtml("<hr>", "generated by the theme, no user input");

    expect(node.type).toBe("trusted-html");
    expect(node.reason).not.toBe("");
  });

  it("does not become text when passed as a child", () => {
    const tree = element("div", {}, trustedHtml("<b>x</b>", "theme markup"));

    expect(tree.children[0]?.type).toBe("trusted-html");
  });

  it("requires a reason a reviewer can read", () => {
    const problems = findVirtualNodeProblems(trustedHtml("<hr>", "   "));

    expect(problems[0]?.message).toContain("why it is trusted");
  });

  it("is visibly different from text in a tree", () => {
    const escaped = text("<script>");
    const raw = trustedHtml("<script>", "an example");

    // A diff shows which one changed; a string would not.
    expect(escaped.type).not.toBe(raw.type);
  });
});

describe("validation", () => {
  it("accepts an ordinary tree", () => {
    expect(
      isValidVirtualNode(
        element("main", { id: "content" }, element("h1", {}, "Title")),
      ),
    ).toBe(true);
  });

  it.each([
    ["an empty tag", ""],
    ["a tag with a space", "my tag"],
    ["a tag starting with a digit", "1tag"],
    ["a tag with an angle bracket", "a>b"],
  ])("rejects %s", (_label, tag) => {
    expect(findVirtualNodeProblems(element(tag))[0]?.message).toContain(
      "not a valid element name",
    );
  });

  it("accepts a custom element name with a hyphen", () => {
    expect(isValidVirtualNode(element("my-widget"))).toBe(true);
  });

  it.each([
    ["a space", 'onclick="x" y'],
    ["a quote", 'a"b'],
    ["an angle bracket", "a>b"],
    ["an equals sign", "a=b"],
    ["a slash", "a/b"],
  ])("rejects an attribute name containing %s", (_label, name) => {
    // A theme can compute an attribute name from data, and a computed name is
    // exactly where markup injection would enter.
    const problems = findVirtualNodeProblems(element("div", { [name]: "v" }));

    expect(problems[0]?.message).toContain("not a valid attribute name");
  });

  it("accepts the attribute names real markup uses", () => {
    expect(
      isValidVirtualNode(
        element("a", {
          href: "/a",
          "aria-label": "Home",
          "data-testid": "link",
          role: "link",
        }),
      ),
    ).toBe(true);
  });

  it("names the path to the problem", () => {
    const problems = findVirtualNodeProblems(
      element("main", {}, fragment(element("bad tag"))),
    );

    expect(problems[0]?.path).toBe("main > fragment > bad tag");
  });

  it("reports every problem, not just the first", () => {
    expect(
      findVirtualNodeProblems(
        element("main", {}, element("a b"), element("c d")),
      ),
    ).toHaveLength(2);
  });

  it("descends through fragments and elements alike", () => {
    const deep: VirtualNode = element(
      "main",
      {},
      fragment(element("section", {}, fragment(element("x y")))),
    );

    expect(findVirtualNodeProblems(deep)).toHaveLength(1);
  });
});

describe("what this deliberately is not", () => {
  it("has no way to attach an event handler", () => {
    // Attributes are strings; a function is not an AttributeValue, so a theme
    // cannot smuggle behaviour into markup that is serialized on a server.
    const tree = element("button", { type: "button" }, "Go");

    expect(
      Object.values(tree.attributes).every((v) => typeof v !== "function"),
    ).toBe(true);
  });

  it("has exactly four node types", () => {
    // Small enough to audit directly. Growing this set is a decision, not a
    // convenience.
    const kinds = [
      element("div").type,
      text("a").type,
      fragment().type,
      trustedHtml("<hr>", "example").type,
    ];

    expect(new Set(kinds).size).toBe(4);
  });
});
